# Criação de Vetores e Arrays em numpy

In [2]:
import numpy as np

# ✔ Array

É o objeto principal do NumPy e pode ter 1, 2, 3 ou mais dimensões.

In [3]:
minha_lista = [1, 2, 3] #vetor é uma array simples de 1 minha
np.array(minha_lista)

array([1, 2, 3])

In [4]:
minha_matriz = [1, 2, 3],[4, 5, 6] #array 2 dimensões é uma matriz
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6]])

## E se eu quiser somar os elementos de uma matriz?

In [5]:
matriz_numpy = np.array(minha_matriz)
np.sum(matriz_numpy)

np.int64(21)

## Criando um array de valores dentro de uma range 

In [7]:
np.arange(0,10, 2) #parecido com for só que muito mais rápido

array([0, 2, 4, 6, 8])

## Array com zeros

In [4]:
np.zeros([3, 2]) #matriz com 3 dimensões e 2 colunas

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [5]:
np.zeros([3, 3, 3]) #linha coluna e profundidade como se fosse um cubo 

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

## Criando matriz de identidade
utilizado muito em algebra linear e etc

In [6]:
np.eye(4) #diagonal preenchida com o número 1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## criando uma sequencia de valores contínua igualmente espaçada

In [13]:
np.linspace(0, 10, 5) #gera 5 valores igualmente espaçados

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## Criação de valores aleatórios entre 0 e 1

In [16]:
np.random.random(2)

array([0.66447201, 0.60693913])

In [17]:
np.random.random(2) * 10 
#números aleatórios entre 0 e 10

array([8.46166122, 3.81541651])

## Método reshape

In [19]:
np.zeros(4)
array = np.zeros(4)
array.shape

(4,)

In [20]:
matriz = np.zeros((3,4))
matriz.shape

(3, 4)