In [2]:
import numpy as np

In [3]:
arr = np.arange(0,30,3)

In [4]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [6]:
print(arr[3])

9


In [8]:
arr[3:]

array([ 9, 12, 15, 18, 21, 24, 27])

In [9]:
arr[[0,5]]

array([ 0, 15])

In [10]:
arr[5:]  = 100

In [11]:
arr

array([  0,   3,   6,   9,  12, 100, 100, 100, 100, 100])

indexação de array de 2 dimensões

In [12]:
arr_2d = np.arange(50).reshape([5,10])

In [13]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [14]:
arr_2d > 20

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [15]:
boleano = arr_2d > 20

In [16]:
arr_2d[boleano]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [17]:
np.logical_and(arr_2d >= 20, arr_2d <=30)

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [18]:
bolleano = np.logical_and(arr_2d >= 20, arr_2d <=30)

In [20]:
arr_2d[bolleano]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])