In [1]:
import numpy as np

In [2]:
array1 = np.arange(0,100,10)
array2 = np.arange(0,50,5)

In [3]:
array1 + array2

array([  0,  15,  30,  45,  60,  75,  90, 105, 120, 135])

In [4]:
array1 - array2

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [5]:
array1 * array2

array([   0,   50,  200,  450,  800, 1250, 1800, 2450, 3200, 4050])

In [6]:
array1 / array2

C:\Users\lhbpc\AppData\Local\Temp\ipykernel_13080\1862955035.py:1: RuntimeWarning: invalid value encountered in divide
  array1 / array2


array([nan,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.])

In [7]:
array1 ** array2

array([                   1,               100000,       10240000000000,
       -2659889346031157248,  1152921504606846976,   187601812243611648,
        1152921504606846976,  2801405922193178624,                    0,
        6702376592317874176])

In [8]:
array1 + 100

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190])

In [9]:
array2 - 100

array([-100,  -95,  -90,  -85,  -80,  -75,  -70,  -65,  -60,  -55])

In [10]:
np.sqrt(array1) #ELE TIRA A RAIZ QUADRADA DO SEU ARRAY

array([0.        , 3.16227766, 4.47213595, 5.47722558, 6.32455532,
       7.07106781, 7.74596669, 8.36660027, 8.94427191, 9.48683298])