In [1]:
import numpy as np

In [2]:
#1.1 Para criar um array com números de 1 a 10:
array = np.arange(1,11)
print(array)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
#1.2 Crie um array de 5 zeros:
array_zero = np.zeros(5)
print(array_zero)

[0. 0. 0. 0. 0.]


In [5]:
#1.3 Crie um array de 5 uns:
array_um = np.ones(5)
print(array_um)

[1. 1. 1. 1. 1.]


In [7]:
#2 Para criar um array com valores espaçados linearmente entre 0 e 50
linear_space = np.linspace(0, 50, 10)
print(linear_space)

[ 0.          5.55555556 11.11111111 16.66666667 22.22222222 27.77777778
 33.33333333 38.88888889 44.44444444 50.        ]


In [20]:
#1.4 Uma matriz identidade é uma matriz quadrada com 1s na diagonal principal:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
#1.5 Acesse os três primeiros elementos:
array = np.array([10,20,30,40,50])
print(array[:3])

[10 20 30]


In [15]:
#1.6. Operações Matemáticas. Eleve cada elemento ao quadrado:
array = np.array([1, 2, 3, 4, 5])
squared_array = array ** 2
print(squared_array)

#Some dois arrays:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

sum_array = array1 + array2

print(sum_array)


[ 1  4  9 16 25]
[5 7 9]


In [16]:
#1.7. Reshape Mude o formato de um array unidimensional para uma matriz 3x3:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
reshaped_array = array.reshape(3, 3)
print(reshaped_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
#1.8. Valores Aleatórios Crie uma matriz 4x4 com valores aleatórios:
array_matriz = np.random.rand(4,4)
print(array_matriz)

[[0.24455399 0.53968633 0.6903851  0.85166857]
 [0.14930186 0.21729666 0.11384972 0.36206547]
 [0.16861913 0.78935801 0.37695728 0.08919414]
 [0.96178445 0.12562885 0.69871985 0.76689628]]
